/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_plugins_kkuevent */

#ifndef _Included_com_androidex_plugins_kkuevent
#define _Included_com_androidex_plugins_kkuevent
#ifdef __cplusplus
extern "C" {
#endif

jint Uevent_OnLoad(JavaVM* vm, void* reserved);
void Uevent_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    find
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_close
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_gpioctrl
  (JNIEnv *, jobject,jint,jint);

JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_gpioread
  (JNIEnv *, jobject,jint);

#ifdef __cplusplus
}
#endif
#endif
