/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_plugins_kkaexparams */

#ifndef _Included_com_androidex_plugins_kkaexparams
#define _Included_com_androidex_plugins_kkaexparams
#ifdef __cplusplus
extern "C" {
#endif
#undef com_androidex_plugins_kkaexparams_MAX_PARAM_SIZE
#define com_androidex_plugins_kkaexparams_MAX_PARAM_SIZE 4096L
/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getAndroidExParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getAndroidExParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    setAndroidExParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkaexparams_setAndroidExParam
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getUUID
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getPass
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getPass
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    setPass
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkaexparams_setPass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getCertsn
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getCertsn
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    setCertsn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkaexparams_setCertsn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getP7cert
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getP7cert
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    setP7cert
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkaexparams_setP7cert
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getNoafter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getNoafter
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getNobefore
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getNobefore
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getState
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getState
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    getUserinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_plugins_kkaexparams_getUserinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_plugins_kkaexparams
 * Method:    setUserinfo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkaexparams_setUserinfo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
