/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_plugins_kkserial */

#ifndef _Included_com_androidex_plugins_kkserial
#define _Included_com_androidex_plugins_kkserial
#ifdef __cplusplus
extern "C" {
#endif

jint Serial_OnLoad(JavaVM* vm, void* reserved);
void Serial_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_plugins_kkserial
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkserial_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eztor_plugins_serial
 * Method:    serial_select
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkserial_select
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_androidex_plugins_kkserial
 * Method:    read
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_androidex_plugins_kkserial_read
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_plugins_kkserial
 * Method:    write
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkserial_write
        (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_plugins_kkserial
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkserial_close
  (JNIEnv *, jobject,jint);


#ifdef __cplusplus
}
#endif
#endif
